---
title: Uw Raspberry Pi instellen
hero_image: images / banner.png
description: Hoe je je Pi voor de eerste keer instelt en start
version: 4
listed: true
copyedit: true
last_tested: "2018/05/16"
steps:
  - 
    title: Invoering
  - 
    title: Wat je nodig zult hebben
  - 
    title: Stel uw SD-kaart in
  - 
    title: Verbind je Pi
  - 
    title: Start je Pi op
  - 
    title: Voltooi de installatie
  - 
    title: Waar kan ik hulp vinden?
  - 
    title: Wat nu?
