---
title: De Raspberry Pi instellen
hero_image: images/banner.png
description: Hoe je de Pi voor de eerste keer instelt en start
version: 4
listed: true
copyedit: true
last_tested: "2018/05/16"
steps:
  - 
    title: Inleiding
  - 
    title: Wat je nodig hebt
  - 
    title: De SD-kaart instellen
  - 
    title: Verbind de Pi
  - 
    title: Start de Pi op
  - 
    title: Voltooi de installatie
  - 
    title: Waar je hulp kunt vinden
  - 
    title: Wat nu?
