title: raspberry-pi-setting-up
hero_image: images/banner.png
description: raspberry-pi-setting-up description
version: 4
listed: false
copyedit: false
last_tested: "2018-05-16"
steps:
  - title: Introduction
  - title: What you will need
  - title: Step title
