title: Setting up your Raspberry Pi
hero_image: images/banner.png
description: How to set up and start your Pi for the first time
version: 4
listed: false
copyedit: false
last_tested: "2018-05-16"
steps:
  - title: Introduction
  - title: What you will need
  - title: Set up your SD card
  - title: Connect your Pi
  - title: Start up your Pi
  - title: Where to find help
  - title: What next?
