---
title: अपने रास्पबेरी पाई की स्थापना
hero_image: छवियों / banner.png
description: पहली बार अपनी पीआई कैसे सेट अप करें और शुरू करें
version: 4
listed: true
copyedit: true
last_tested: "2018/05/16"
steps:
  - 
    title: परिचय
  - 
    title: तुम क्या आवश्यकता होगी
  - 
    title: अपना एसडी कार्ड सेट अप करें
  - 
    title: अपने पीआई कनेक्ट करें
  - 
    title: अपनी पीआई शुरू करो
  - 
    title: सेटअप खत्म करो
  - 
    title: सहायता कहां मिलें
  - 
    title: आगे क्या?
