---
title: あなたのラズベリーパイを設定する
hero_image: images / banner.png
description: 初めてPiをセットアップして起動する方法
version: 4
listed: true
copyedit: true
last_tested: "2018-05-16"
steps:
  - 
    title: 前書き
  - 
    title: あなたが必要とするもの
  - 
    title: SDカードを設定する
  - 
    title: あなたのPiを接続
  - 
    title: Piを起動する
  - 
    title: セットアップを完了してください
  - 
    title: ヘルプを見つける場所
  - 
    title: 次は何？
