---
title: Postavljanje vašeg malina Pi
hero_image: slike / banner.png
description: Kako postaviti i pokrenuti svoj Pi po prvi put
version: 4
listed: true
copyedit: true
last_tested: "2018/05/16"
steps:
  - 
    title: Uvod
  - 
    title: Ono što će vam trebati
  - 
    title: Postavite SD karticu
  - 
    title: Povežite svoj Pi
  - 
    title: Pokrenite Pi
  - 
    title: Završite postavljanje
  - 
    title: Gdje pronaći pomoć
  - 
    title: Što dalje?
