---
title: راه اندازی Raspberry Pi
hero_image: images / banner.png
description: چگونه برای اولین بار شما Pi را راه اندازی و شروع کنید
version: 4
listed: true
copyedit: true
last_tested: "2018-05-16"
steps:
  - 
    title: معرفی
  - 
    title: آنچه شما نیاز دارید
  - 
    title: کارت SD خود را تنظیم کنید
  - 
    title: پی پی خود را وصل کن
  - 
    title: راه اندازی Pi خود را
  - 
    title: پایان دادن به پایان
  - 
    title: از کجا پیدا کردن کمک
  - 
    title: بعدش چی؟
