---
title: Sefydlu eich Pi Mws
hero_image: delweddau / banner.png
description: Sut i sefydlu a dechrau eich Pi am y tro cyntaf
version: 4
listed: true
copyedit: true
last_tested: "2018-05-16"
steps:
  - 
    title: Cyflwyniad
  - 
    title: Beth fydd ei angen arnoch chi
  - 
    title: Gosodwch eich cerdyn SD
  - 
    title: Cysylltwch â'ch Pi
  - 
    title: Dechreuwch eich Pi
  - 
    title: Gorffen y gosodiad
  - 
    title: Ble i ddod o hyd i help
  - 
    title: Beth nesaf?
