---
title: Richten Sie Ihren Raspberry Pi ein
hero_image: Bilder / Banner.png
description: So richten Sie Ihren Pi ein und starten ihn zum ersten Mal
version: 4
listed: true
copyedit: true
last_tested: "2018-05-16"
steps:
  - 
    title: Einführung
  - 
    title: Was wirst du brauchen
  - 
    title: Richten Sie Ihre SD-Karte ein
  - 
    title: Verbinde dein Pi
  - 
    title: Starte deinen Pi
  - 
    title: Beenden Sie das Setup
  - 
    title: Wo finde ich Hilfe?
  - 
    title: Was als nächstes?
