---
title: Configurarea fructelor de zmeura Pi
hero_image: images / banner.png
description: Cum să configurați și să porniți Pi pentru prima dată
version: 4
listed: true
copyedit: true
last_tested: "2018-05-16"
steps:
  - 
    title: Introducere
  - 
    title: Ce vei avea nevoie
  - 
    title: Configurați cardul SD
  - 
    title: Conectează-ți Pi
  - 
    title: Porniți-vă Pi
  - 
    title: Finalizați configurarea
  - 
    title: Unde găsiți ajutor
  - 
    title: Ce urmează?
