---
title: Configurando seu Raspberry Pi
hero_image: images/banner.png
description: Como configurar e iniciar seu Pi pela primeira vez
version: 4
listed: true
copyedit: true
last_tested: "16/05/2018"
steps:
  - 
    title: Introdução
  - 
    title: O que você vai precisar
  - 
    title: Selecione seu cartão SD
  - 
    title: Conectando dispositivos em seu Raspberry Pi
  - 
    title: Iniciando seu Raspberry Pi
  - 
    title: Concluindo a configuração
  - 
    title: Onde encontrar ajuda
  - 
    title: Próxima etapa
