---
title: Menyiapkan Raspberry Pi Anda
hero_image: images / banner.png
description: Cara mengatur dan memulai Pi Anda untuk pertama kalinya
version: 4
listed: true
copyedit: true
last_tested: "2018-05-16"
steps:
  - 
    title: pengantar
  - 
    title: Apa yang Anda butuhkan
  - 
    title: Siapkan kartu SD Anda
  - 
    title: Hubungkan Pi Anda
  - 
    title: Mulai Pi Anda
  - 
    title: Selesaikan pengaturan
  - 
    title: Di mana menemukan bantuan
  - 
    title: Apa selanjutnya?
