---
title: הגדרת Pi שלך פטל
hero_image: תמונות / banner.png
description: כיצד להגדיר ולהתחיל את פי בפעם הראשונה
version: 4
listed: true
copyedit: true
last_tested: "2018-05-16"
steps:
  - 
    title: מבוא
  - 
    title: מה שאתה תצטרך
  - 
    title: הגדר את כרטיס ה- SD שלך
  - 
    title: חבר- Pi me
  - 
    title: התחל את פיי
  - 
    title: סיים את ההתקנה
  - 
    title: היכן ניתן למצוא עזרה
  - 
    title: מה הלאה?
