---
title: Configuration de votre Raspberry Pi
hero_image: images / banner.png
description: Comment configurer et démarrer votre Pi pour la première fois
version: 4
listed: true
copyedit: true
last_tested: "2018-05-16"
steps:
  - 
    title: introduction
  - 
    title: Ce dont tu auras besoin
  - 
    title: Configurez votre carte SD
  - 
    title: Connectez votre Pi
  - 
    title: Démarrez votre Pi
  - 
    title: Terminer l'installation
  - 
    title: Où trouver de l'aide
  - 
    title: Que faire ensuite?
