---
title: إعداد Raspberry Pi الخاص بك
hero_image: صور / banner.png
description: كيفية إعداد وبدء Pi الخاص بك لأول مرة
version: 4
listed: true
copyedit: true
last_tested: "2018/05/16"
steps:
  - 
    title: المقدمة
  - 
    title: ما سوف تحتاجه
  - 
    title: قم بإعداد بطاقة SD الخاصة بك
  - 
    title: قم بتوصيل Pi الخاص بك
  - 
    title: بدء بي الخاص بك
  - 
    title: الانتهاء من الإعداد
  - 
    title: أين تجد المساعدة
  - 
    title: ماذا بعد؟
