---
title: Raspberry Pi 설정하기
hero_image: images/banner.png
description: Raspberry Pi를 설치하고 시작하는 법
version: 4
listed: true
copyedit: true
last_tested: "2018-05-16"
steps:
  - 
    title: 소개
  - 
    title: 준비물
  - 
    title: SD 카드를 선택하세요
  - 
    title: Raspberry Pi 연결하기
  - 
    title: Raspberry Pi 시작하기
  - 
    title: 설정 마무리하기
  - 
    title: 문의할 곳
  - 
    title: 다음은?
