---
title: 라즈베리 파이 설정하기
hero_image: images / banner.png
description: Pi를 처음 설치하고 시작하는 방법
version: 4
listed: true
copyedit: true
last_tested: "2018-05-16"
steps:
  - 
    title: 소개
  - 
    title: 필요한 것
  - 
    title: SD 카드 설정
  - 
    title: Pi 연결
  - 
    title: 파이 시작
  - 
    title: 설정 완료
  - 
    title: 도움을 얻을 수있는 곳
  - 
    title: 다음은?
