---
title: Nastavenie vašej maliny Pi
hero_image: images / banner.png
description: Ako prvýkrát nastaviť a spustiť Pi
version: 4
listed: true
copyedit: true
last_tested: "2018-05-16"
steps:
  - 
    title: úvod
  - 
    title: Čo budete potrebovať
  - 
    title: Nastavte SD kartu
  - 
    title: Pripojte svoj Pi
  - 
    title: Spustite Pi
  - 
    title: Dokončite nastavenie
  - 
    title: Kde nájsť pomoc
  - 
    title: Čo ďalej?
