---
title: Menyediakan Raspberry Pi anda
hero_image: imej / banner.png
description: Bagaimana untuk memulakan dan memulakan Pi anda buat kali pertama
version: 4
listed: true
copyedit: true
last_tested: "2018-05-16"
steps:
  - 
    title: Pengenalan
  - 
    title: Apa yang anda perlukan
  - 
    title: Sediakan kad SD anda
  - 
    title: Sambungkan Pi anda
  - 
    title: Mulakan Pi anda
  - 
    title: Selesaikan persediaan
  - 
    title: Di mana untuk mencari bantuan
  - 
    title: Apa selepas ini?
