---
title: আপনার রাস্পবেরি পাই সেট আপ
hero_image: ইমেজ / banner.png
description: কিভাবে সেট আপ এবং প্রথমবার জন্য আপনার Pi শুরু
version: 4
listed: true
copyedit: true
last_tested: "2018-05-16"
steps:
  - 
    title: ভূমিকা
  - 
    title: আপনার যা দরকার
  - 
    title: আপনার এসডি কার্ড সেট আপ করুন
  - 
    title: আপনার পাই সংযুক্ত করুন
  - 
    title: আপনার পাই শুরু করুন
  - 
    title: সেটআপ শেষ করুন
  - 
    title: কোথায় সাহায্য খুঁজে পেতে
  - 
    title: এরপর কী?
