---
title: Configurare il tuo Raspberry Pi
hero_image: images / banner.png
description: Come configurare e avviare il Pi per la prima volta
version: 4
listed: true
copyedit: true
last_tested: "2018/05/16"
steps:
  - 
    title: introduzione
  - 
    title: Di cosa avrai bisogno
  - 
    title: Configura la tua scheda SD
  - 
    title: Collega il tuo Pi
  - 
    title: Avvia il tuo Pi
  - 
    title: Completa il setup
  - 
    title: Dove trovare aiuto
  - 
    title: Cosa succederà?
