---
title: Ahududu Pi'nizi kurma
hero_image: images / banner.png
description: Pi'nizi ilk kez nasıl kurabilir ve başlatabilirsiniz?
version: 4
listed: true
copyedit: true
last_tested: "2018/05/16"
steps:
  - 
    title: Giriş
  - 
    title: Neye ihtiyacınız olacak?
  - 
    title: SD kartınızı ayarlayın
  - 
    title: Pi'nizi bağlayın
  - 
    title: Pi'nizi başlatın
  - 
    title: Kurulumu bitir
  - 
    title: Nerede yardım bulabilirim
  - 
    title: Sırada ne var?
